import { Metadata } from 'next';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export const metadata: Metadata = { title: 'Privacy Policy', description: 'DynamoDM Privacy Policy' };

export default function PrivacyPage() {
  const sections = [
    { title: '1. Information We Collect', content: 'We collect information you provide directly: name, email, Instagram Business Account data (username, profile, followers count), automation rules you create, and payment information processed by Razorpay. We also collect usage data such as DM logs, analytics events, and lead capture data generated by your automations.' },
    { title: '2. How We Use Your Information', content: 'We use your information to provide, maintain, and improve our services; process transactions; send transactional emails; provide customer support; monitor and analyze usage patterns; and comply with legal obligations. We do not sell your personal information to third parties.' },
    { title: '3. Instagram & Meta Data', content: 'When you connect your Instagram account, we receive and store your Instagram Business Account ID, access token (encrypted at rest), username, and profile information. We use this solely to send DMs on your behalf as configured by your automation rules. We comply with all Meta Platform Terms and Instagram API policies.' },
    { title: '4. Data Security', content: 'We implement industry-standard security measures including AES-256-GCM encryption for stored access tokens, HMAC signature verification for webhooks, JWT-based authentication, HTTPS enforcement, and rate limiting. However, no method of transmission over the Internet is 100% secure.' },
    { title: '5. Data Retention', content: 'We retain your account data for as long as your account is active. Analytics events are retained for up to 1 year. DM logs are retained for 90 days. You may request deletion of your data at any time by contacting us.' },
    { title: '6. Your Rights', content: 'You have the right to access, update, or delete your personal information; export your data (leads, DM logs); disconnect your Instagram account at any time; close your account; and opt out of marketing communications.' },
    { title: '7. Contact Us', content: 'If you have questions about this Privacy Policy, please contact us at privacy@dynamodm.io.' },
  ];

  return (
    <>
      <Navbar />
      <main className="pt-28 pb-16">
        <div className="container-sm">
          <h1 className="text-4xl font-semibold tracking-tight">Privacy Policy</h1>
          <p className="mt-2 mb-10 text-sm text-[var(--text-muted)]">Last updated: June 2026</p>
          <div className="space-y-8">
            {sections.map((s) => (
              <div key={s.title}>
                <h2 className="mb-2 text-lg font-semibold">{s.title}</h2>
                <p className="text-[15px] leading-8 text-[var(--text-secondary)]">{s.content}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
